### ISSUE TITLE
Version 0.0.1 fails with UnusedImport

### ISSUE THREAD

**Issue by tmcgilchrist** [jystic/purescript-jack#12]
```
[1/1 UnusedImport] bower_components/purescript-jack/src/Jack/Tree.purs:20:1

  20  import Data.Monoid ((<>))
      ^^^^^^^^^^^^^^^^^^^^^^^^^

  The import of module Data.Monoid is redundant

```

Seems like it needs a newer version published. If you install the master version using
`bower install https://github.com/jystic/purescript-jack.git#master`
it doesn't complain about anything.

**Comment by damncabbage** [comment]
Fixed by https://pursuit.purescript.org/packages/purescript-jack/0.0.2; thanks, @jystic.

**Comment by jacobstanley** [comment]
👍

**Comment by tmcgilchrist** [comment]
Cheers 🍻
